#!/usr/bin/env bash
set -euo pipefail

required=(
  SYNCBASE_PROD_POSTGRES_OWNER_PASSWORD
  SYNCBASE_PROD_WEB_DB_PASSWORD
  SYNCBASE_PROD_WORKER_DB_PASSWORD
  SYNCBASE_PROD_MCP_DB_PASSWORD
  SYNCBASE_PROD_ADMIN_USERNAME
  SYNCBASE_PROD_ADMIN_PASSWORD_BCRYPT
  SYNCBASE_PROD_MCP_TOKEN
  SYNCBASE_PROD_MCP_ALLOWED_HOSTS
  SYNCBASE_PROD_PUBLIC_BASE_URL
  SYNCBASE_EC2_HOST
  SYNCBASE_EC2_USER
  SYNCBASE_EC2_SSH_PRIVATE_KEY
  SYNCBASE_EC2_KNOWN_HOSTS
)
for name in "${required[@]}"; do
  [[ -n "${!name:-}" ]] || { echo "missing production input: $name" >&2; exit 64; }
done

case "$SYNCBASE_PROD_PUBLIC_BASE_URL" in
  https://*) ;;
  *) echo "SYNCBASE_PROD_PUBLIC_BASE_URL must use https" >&2; exit 64 ;;
esac
printf 'PRODUCTION_INPUTS_VERIFIED\n'
